### ISSUE TITLE
LibHealComm not working in latest Wrath beta release

### ISSUE THREAD

**Issue by vuryn** [michaelnpsp/Grid2#101]
Healing predictions with LibHealComm-4.0 are not working in Wrath Classic since the last Wrath beta release. While direct heals still show up, HoTs and channeled heals do not. 

I was able to restore the desired behavior by partially reverting the changes to [Grid2.toc](https://github.com/michaelnpsp/Grid2/commit/4b89f3c2c570cea515f90a41041accf7ee3b14a4#diff-0ac827fa0e083dd5a1084db03088dc4bad95bffd702da25650daae5eaa95d535). Adding
```
Libs\LibHealComm-4.0\ChatThrottleLib.lua
Libs\LibHealComm-4.0\LibHealComm-4.0.lua
```
in the Lib section solved the problem for me.

**Comment by michaelnpsp** [comment]
If you read the 2.1.2-beta chages:
"Removed LibHealComm-4 library in classic versions. Grid2 can still use libhealcomm-4 but it should be installed separately."

LibHealComm-4 is not included with grid2 anymore because this library runs very bad in wotlk. But you can install LibHealComm-4 addon separately, you can open curseforge web/app and  install LibHealComm-4.

If the library exist in the sytem Grid2 still can use it. You can configure which API to use (Blizzard or LibHealComm) in:
Statuses/Health&Heals/incoming-heals

**Comment by vuryn** [comment]
Thank you for your quick response @michaelnpsp. It helped me track down the actual problem I was encountering. 
In the "heals-incoming" status, I have LibHealComm selected under "Heals API".

![grafik](https://user-images.githubusercontent.com/106357104/215169552-2056f24a-1bdb-4081-ba80-4c8f307eec6c.png)

As I did not have LibHealComm installed in the global namespace, Grid silently fell back to the Blizzard API (therefore not showing HoTs). However, the dropdown default selection and also the checkmark still indicate that LibHealComm is used. 

Steps to reproduce:
1. Select LibHealComm as Heal API (Statuses > Health&Heals > heals-incoming)
2. Remove or rename LibHealComm from Interface/Addons folder
3. Reload interface

Expected behavior:
- LibHealComm disappears as an option for Heals API

Actual behavior:
- LibHealComm is still selected as Heals API (see image above). However, Blizzard API is silently used as fallback.

**Comment by vuryn** [comment]
After some further research, I think I might have found the issue:

- When Grid2 loads, it checks if [LibHealComm is available](https://github.com/michaelnpsp/Grid2/blob/main/modules/StatusHealth.lua#L604) to decide whether or not to use LHC or the Blizzard API.
- For me, this was not the case, as I did not have it installed globally.
- After Grid2, however, another addon (in my case ZPerl) initialized and loaded its own LibHealComm dependency. This makes it available globally and LibStub will find it.
- If I now open the Grid2 options panel, no warning will be shown, as [this](https://github.com/michaelnpsp/Grid2/blob/main/Options/modules/statuses/StatusHealth.lua#L9) now returns a valid LibHealComm reference and [this](https://github.com/michaelnpsp/Grid2/blob/main/Options/modules/statuses/StatusHealth.lua#L80) check will be true, therefore never showing the error message.

So right now, there is a race condition depending on other addons with a LHC dependency loading the lib before or after Grid2 initializes.

**Comment by Blaticus** [comment]
"because this library runs very bad in wotlk" what does this mean? I've been using LibHealComm with Grid2 since the return of Classic in 2019. The Blizzard API has a problem with preemptively removing incoming healing indicators when the spell is still "in the air" (i.e. as the player's cast is finishing but *before* the healing has taken effect) which is jarring. Outright removing the lib means that if I want to use LibHealComm still, I'll need to get all of the other healers in my raid that are using grid2 to go install the lib separately which is a headache.

If there's a real performance-related reason then I can understand removing it, but I am confused.

**Comment by michaelnpsp** [comment]
All raid frames using libhealcomm have a lot of tickets with people claiming that they have frame drops and stuttering in 25-man raids. And even if the addon is configured to use Blizzard API, the LibHealComm library can not be disabled so it is always using cpu and network resources.
And the library is really not active maintained, so healcomm issues are a headache because i can do nothing about any libhealcomm related issue.
Sorry  the only way that i know to fix this mess is to remove the library from Grid2, people not having issues with healcom can install the healcom standalone addon that is available in CurseForge.

**Comment by Blaticus** [comment]
Thank you for the response, understood! Thank you for your hard work maintaining Grid2! <3

**Comment by michaelnpsp** [comment]
This issue should be fixed in 2.1.3-wrath.
Now LibHealComm loading process is delayed so grid2 should always detect healcom libraries loaded by another addons.

**Comment by Loregon** [comment]
And you can tell us how the GRID on the api will interact with other healers on other raid frames that have HealComm. Will they see at least direct healings

**Comment by michaelnpsp** [comment]
Grid2 does not interact with other raid frames.
