### ISSUE TITLE
[Question] 10man layout

### ISSUE THREAD

**Issue by sMuve** [michaelnpsp/Grid2#103]
Hi there,
I wanted to create a layout for 10mans (in WotLK) with a 2 (rows) x 5 (columns) dimension.
Row 1 should be group 1 and row 2 should be group 2.

Therefore I have created a layout in Layouts -> Editor and configured it this way:
![image](https://user-images.githubusercontent.com/25771494/216766878-8112b436-0cc6-4001-86a9-828208276998.png)
![image](https://user-images.githubusercontent.com/25771494/216766890-1cdb5189-d214-46d1-8d88-d50d3fca2dd5.png)

These are my Layouts > General settings:
![image](https://user-images.githubusercontent.com/25771494/216767210-f10f3281-c3f5-4716-b849-897fa53f83a0.png)

However here is the difference between what I desire and what I get:
![image](https://user-images.githubusercontent.com/25771494/216766873-99e05c5d-d978-4f12-8899-171a694c72af.png)

In addition I tried to create two players configs. One with 5 Columns and 1 Unit / Column and only Group 1 assigned and a second one for Group 2. Unfortunately it did also no solve my problem :(

Can someone help me with this?

**Comment by michaelnpsp** [comment]
You have to create two players groups/tabs in the layout editor: players(1) and players(2)
players(1) -> to display group 1 players (Check only group 1 in Groups section), 1 column, 5 units per column
players(2) -> to display group 2 players (Check only group 2 in Groups section), 1 column, 5 units per column

But you dont need to use the layout editor because grid2 already includes a layout like this:  simply select "By Group" layout.

**Comment by sMuve** [comment]
I tested it and checked it again. Using "By Group" as "By Raid Size" layout will result in this
![image](https://user-images.githubusercontent.com/25771494/216789401-5da50af5-d93d-4cd6-afa5-80908d1e1cae.png)

The same happens when I use the suggested settings for players(1) and player(2).

I would like to achieve such a layout:
![image](https://user-images.githubusercontent.com/25771494/216789511-a1366b28-04fc-43e2-aed6-9d3244a2bf2c.png)

**Comment by michaelnpsp** [comment]
Goto General/Appearance/Layout Disposition and in "Groups Orientation" option select: "Horizontal"
And if you want the Pets to the right (not behind the last players group), you have to Detach pets group and move the pets group the desired position.

**Comment by sMuve** [comment]
Oh that's what I have missed. Thank you very much!

Maybe one - not so related - question: Can I also have different positions for different layouts? (e.g. 10man at the bottom middle of my screen and 5man to the left middle)

**Comment by michaelnpsp** [comment]
There are two posibilites:
1. The most powerfull option is to enable themes (in general tab), then you can create several themes and you can setup different positions, sizes and appearances for  different party/raids/classes/specs, etc. because each created theme has its own Layouts/Appearance and Indicators Tab configuration.
2. Less powerfull but more easy to setup, using a trick, if you detach some group (for example enabling the "Detach Pets groups" option), the addon will store independend positions for different layouts.

**Comment by sMuve** [comment]
Okay, I have used a mix of both :)
1. to adjust the positioning of my frames depending on the group/raid size
2. to adjust the positioning of my pet frames for each theme from 1.
Thank you very much for your help!
