### ISSUE TITLE
Raid Debuffs

### ISSUE THREAD

**Issue by cruzerthebruzer** [michaelnpsp/Grid2#11]
I've been playing around with the alpha version. I'm incredibly excited about the debuff additions.

Is there plans or thoughts about adding a *not* raid buff? Or is there a way to do that? 

Use case:
I want a row of a few `dispellable debuffs` and I want to have `all other debuffs` without duplication. Might be an unrealistic want and maybe I should just use dispellable debuffs as a health bar color or something. This very well could be a duplicate of #10. 

To add further clarification, is there a way to get raid debuffs + all non dispellable debuffs in the same item? 

Also, are you looking for extra contributors?

Thanks for the best raid frame addon out there. 👍

**Comment by michaelnpsp** [comment]
_To add further clarification, is there a way to get raid debuffs + all non dispellable debuffs in the same item?_
You can link several debuffs statuses (for example: boss debuffs group + no dispellable debuffs group) to the same "icons" (plural) indicator.

**Comment by cruzerthebruzer** [comment]
I guess my further clarification was misleading. Is there a way to do that without duplicating? Is there any upside to using raid debuffs vs. debuffs besides the user friendliness of it? If I have a row of dispellable debuffs, and a row of non dispellable debuffs does that miss any coverage? Doesn't seem like it would but I don't know the magic of raid debuffs :)

**Comment by michaelnpsp** [comment]
"Dispellable debuffs + Non dispellable debuffs" will display all debuffs on the unit (a raid debuff is nothing special it's a standard debuff).
And about the "raid debuffs vs debuffs" question: they are differents ways to manage the same debuffs, some people prefer to use the raid debuffs module, other people use debuffs groups.
Raid debuffs module is more cpu efficient, but needs more configuration (all debuffs must be collected and added to the configuration).
Its advised to not use too many debuffs groups + icons (plural) indicators because this method uses much more CPU. The only exception is debuffs groups composed only of whitelisted debuffs,  because the implementation of whitelists is very fast (no function calls, no complex filters, a simple table lookup to check for the debuff).

**Comment by cruzerthebruzer** [comment]
Thanks for the insight. This is a great addon. Is there a discord or something like it?
