### ISSUE TITLE
[Feature Request] Show Current Dungeon Debuff List

### ISSUE THREAD

**Issue by martheli** [michaelnpsp/Grid2#142]
When you open this window, it should auto show you your dungeon or raid that you are currently in

![image](https://github.com/michaelnpsp/Grid2/assets/20176169/9a6d2bc7-6aa9-4c53-b80b-529c1cef03ee)

**Comment by martheli** [comment]
Why isn't this something that can be added? Seems like a big time safer for older dungeons.

**Comment by michaelnpsp** [comment]
Due to some AceConfig library limitations (for example the library does not notify when the configuration window is opened)  its not easy/straight forward to implement.

**Comment by michaelnpsp** [comment]
Update to 2.3.17-beta, the "auto open debuffs for current instance" toggle  in general options should be checked to enable this feature. The debuffs are updated only when the configuration window is opened or reopened.

**Comment by martheli** [comment]
Im on latest version:
![image](https://github.com/michaelnpsp/Grid2/assets/20176169/31640f31-7cd9-4877-a1c0-da3d8b6cfc0a)

That option is not available to select:
![image](https://github.com/michaelnpsp/Grid2/assets/20176169/9684d61a-d30d-4ab6-90d5-a7ed84bcf870)
![image](https://github.com/michaelnpsp/Grid2/assets/20176169/2f520e3b-e482-4b7b-b6fc-98a4973fd379)

**Comment by michaelnpsp** [comment]
Sorry, my instructions were not very clear. The option is in general settings tab of raid debuffs options:
Statuses/Raid Debuffs /General Settings Tab/Auto open debuffs option.

**Comment by martheli** [comment]
perfect, tested it and works great!

**Comment by martheli** [comment]
I found an issue with it. I went into Azure vault and it was showing wrong dungeon:
![image](https://github.com/michaelnpsp/Grid2/assets/20176169/b9c3510b-0e2a-4966-a13d-d42b6793233f)

**Comment by michaelnpsp** [comment]
Azure Vault is working fine for me, but i did test just in the starting zone of the dungeon. 
If the addon cannot detect the dungeon should be due to the game is reporting and incorrect map/dungeon for some subzone/submap in the dungeon. This happens in some dungeons subzones all along several expansions due to incorrect data stored in the game that was never fixed.
If you can go to the wrong zone and repeat the glitch, you can enabled debug info for Grid2RaidDebufs nidyke in General/"About" Tab and report back what zone is reported by the game, the chat should display some  message like, when you enter first time in the glitched subzone or if you reload the UI in this zone:

**Grid2: DEBUG Grid2_Grid2RaidDebuffs Zone[Azure Vault] C_MapID[2073] EjID[1203] mapID[102515] Status [raid-debuffs]: 21  raid debuffs loaded from [1203]**
