### ISSUE TITLE
[Question / Feature request] Add players to name list in custom layout with mouseover macro

### ISSUE THREAD

**Issue by Elliath21** [michaelnpsp/Grid2#146]
Hello.

I started using custom layout to create separate group for players I want to buff as Augmentation Evoker. When raiding in PuG, it is a bit time consuming to add names and realms of players into the list. Blizzard copy name functionality copies only the name without the realm.

I would like to ask, if it would be possible to add player-realm to name list using a mouseover macro and to clear the name list using another macro.

Thank you.

**Comment by LiamGBR** [comment]
@Elliath21 did you find a way to do this? installing entire seperate addon vuhdo just to use private tank + macro is not something id want to do

**Comment by Elliath21** [comment]
@LiamGBR Sadly no. I ended up setting up VuhDo. It does have an advantage - when you use VuhDo only for private tanks, you can set up OmniCD to show only for VuhDo frames. At least I wanted it that way.

**Comment by michaelnpsp** [comment]
Im planning to add a command line argument with a syntax like:
/grid2 namelist | nl   [headerType]   @mouseover
/grid2 namelist | nl   [headerType]   player_name
/grid2 namelist | nl   [headerType]   clear
To add/remove/clear player names  to the namelist defined in the currect active layout. 
Theses commands added to some macros and keybindings should allow to manage a private tanks name list.

**Comment by michaelnpsp** [comment]
Implemented in 2.6.3-beta.
The chat command only works with custom layoutst defined using the Grid2 Layout Editor, and a namelist must be enabled in some header of  the layout.  Documentation and usage examples for future reference:

Usage:

**/grid2 namelist [headerType]  clear | @mouseover | PlayerName
/gr2 nl [headerType]  clear | @mouseover | PlayerName**

Examples:

_Add or Remove the player under the mouse pointer to the first namelist of the currect active layout._
**/gr2 nl @mouseover**

Add or Remove JohnSmith player from Arathor server to the "myTanks" header defined in the active layout. Displaying and error if the header or namelist dont exist in the active layout.
**/gr2 nl myTanks JohnSmith-Arathor**

Clear all players of the first nameList defined in the active layout.
**/gr2 nl clear**

Clear all players from the "tanks"  header in the active layout (headerType=tanks).
**/gr2 nl tanks clear**

**Comment by LiamGBR** [comment]
Thats great thanks the only thing I would mention after setup and testing is maybe to be able to scale the second header frames seperately as I think when using the new raid size setting to resize frames it might also resize my "private" header. other potential thing would be seperate anchors so second header can grow from top left while other frames can still grow from bottom left.

https://github.com/michaelnpsp/Grid2/assets/26609549/d8a33c5c-e9af-4b29-902a-8938b43b0fca

**Comment by michaelnpsp** [comment]
Most requested features were already implemented but not exposed in the configuration.

See "Header Types" Tabs in "General / ... /  Appearance / Layout Disposition".

I added a new **"Others"** tab to setup the behaviour of custom defined headers in the Layout Editor.
So now in "Layout Disposition" there are tabs to configure frame size, anchors and orientation for each header type:

**"players,  pets, self,  target, focus, bosses and others".**

I added a new **"Lock Frame Size"** option too for each header type, if this option is enabled, unit frames inside the header cannot  by resized using the  "Layouts/By Raid Size" settings. 
This allows to setup a fixed width and height for bosses/player/target/focus/others headers.

Important: "Others" headers are headers with a customized header type. Simply goto the layout editor, click on the desired header, and change the "Header Type" text, for example "tanks" or "private tanks" or wherever you want, instead of "players".
