### ISSUE TITLE
[Question] Copy Raid Debuffs

### ISSUE THREAD

**Issue by martheli** [michaelnpsp/Grid2#148]
I set up my resto shaman raid debuffs and then if I change to another character is there a way to share the same raid debuffs list that I have enabled/disabled?

**Comment by michaelnpsp** [comment]
Not possible with different profiles. but you can use use the same profile for several characters.
You can enable themes (in general tab) and setup a different theme for each class/role/spec or even group or instance type,
Different appearances can be configured for each theme. 
By default all themes share indicators and statuses, but optionally load conditions can be defined to enable different indicators/statuses for each theme.
Some players prefer to setup only one profile with different themes, because its faster to setup shared things and even to manage backups.
