### ISSUE TITLE
[Bug] Percent Stack Size Not Showing Correctly In Raids

### ISSUE THREAD

**Issue by martheli** [michaelnpsp/Grid2#152]
I have an indicator for earth shield and I have the stack text set to a percent like this:

![image](https://github.com/michaelnpsp/Grid2/assets/20176169/4c68226a-6b5b-4b4c-87df-b197f5c945ae)

There seems to be an issue in raids where if I apply earth shield to people the stack text is correct like this:
![image](https://github.com/michaelnpsp/Grid2/assets/20176169/b236a9f2-d856-4cfc-b6be-7f7d8ccd6dab)

But If I apply earth shield to anyone in the first group of the raid the stack size is much larger
![image](https://github.com/michaelnpsp/Grid2/assets/20176169/8897422d-7ee8-4f28-a71e-30d3243ebb95)

**Comment by michaelnpsp** [comment]
For future reference, crazy bug:
The game ignores the SetFont() command if the frame unit is not visible, but only on the  second SetFont() call (the fontstring must have a previous font and size assigned to trigger the issue). 
Added a ugly fix to delay the font assignment until the frame becomes visible.
Not sure if the fix will work correctly because i dont know exactly which triggers this game behavior.

**Comment by michaelnpsp** [comment]
2.3.16-beta version may fix this issue.
