### ISSUE TITLE
Icons Indicator not aligned with location

### ISSUE THREAD

**Issue by martheli** [michaelnpsp/Grid2#158]
I have an icons indicator set to location bottom with no offset. When one icon shows up it's not aligned to the center:

![image](https://github.com/michaelnpsp/Grid2/assets/20176169/616f0f1b-54f6-40c8-8578-1918cdf1abf3)

Is this how it's supposed to be? It seems it should be aligned to the center of the frame and grow outwards while staying center aligned.

**Comment by michaelnpsp** [comment]
Yes this is working as intended 
The addon does not adjust indicator positions on the fly, this only happens once, when the selected layout is loaded. 
In this case the game creates a 3x3 grid of icons (due to max icons=3 and icons per row=3) and centers the 3x3 grid once, just when the layout is loaded (the position calculation is done assuming all 9 icons are going to be displayed).
