### ISSUE TITLE
Show if missing not working

### ISSUE THREAD

**Issue by asiantuntija** [michaelnpsp/Grid2#161]
Hey, I tried adding a _show if missing indicator_ for my personal buffs in Classic, but the status won't show up. If remove the show if missing check, then the status spawns correctly when I buff myself, so everything should be set correctly otherwise.

![image](https://github.com/michaelnpsp/Grid2/assets/8327991/387ed7d1-9db8-4239-ab1e-d67b1af6e363)
![image](https://github.com/michaelnpsp/Grid2/assets/8327991/28ef7727-ae29-407b-a14e-cbb6e2b84577)

**Comment by michaelnpsp** [comment]
"Show if missing" option is not implemented for  buffs groups linked to "icons(plural)" indicators, you must link the status to a icon(single) or a square indicator.

**Comment by asiantuntija** [comment]
Seems also that only the first item listed in the status works. Is this hard to implement to the icons indicator and make the whole list of statuses work?

Basically, if this works the same as having single buff and single icon indicator, it would be more intuitive to the user if there wasn't the checkbox at all. That way you would be guided to use that single buff interface.

**Comment by michaelnpsp** [comment]
The option does not work in the way you are thinking. 

This option cannot be used to display when some buff is missing, the status is only enabled when "all buff" are missing.
So it has no sense to add different kind of buffs in the list, this option was designed to monitorize and group similar buffs, for example, if you want to track when mage intellect buff is missing you can add all kinds of intellect buffs:
**Arcane Intellect
Arcane Brillance**
And the status is only activated when none of the buffs exist, because you simply want to know which players are lacking intellect, to reapply the buff to them

After explaining this i think is obvious because only the first buff in the list is displayed (or a generic icon if the texture of the first buff cannot be retrieved):
if none of the buffs exist in a player, which icon buff should be displayed ?, the first buff ? the last buff ? random select ? It does not matter, so for consistency the addon always display the same icon, the first buff in the list.

**Comment by asiantuntija** [comment]
Right, it makes sense when you explain it like that. It behaves different from the buffs group that spawns every buff that is in the list, the negative (show if missing) requires all of the buffs to match (be missing).

 Would be neat to have same functionality, maybe add a checkbox that ask to match all or single.

Anyways, I can do the functionality now with single statuses of course, just that I feel it would be tidier if all of the buffs were in a single list.
