### ISSUE TITLE
Opposite faction players in your party appear "greyed out" as if they are far away from you

### ISSUE THREAD

**Issue by dimitriskolios** [michaelnpsp/Grid2#163]
On Retail, opposite faction players in your party appear "grayed out" as if they are far away from you, even if they stand right next to you. This happens on the outer world only, not inside dungeons

**Comment by michaelnpsp** [comment]
There are several ways to "gray out" unit frames depending of the grid2 configuration. 
So check out your range status setup (if this is the status used in your config to gray out unit frames).
By default if your toon is a healer grid2 gray out a unit frame if the player cannot be healed, in this case is the normal behaviour because in open world opposite faction players are enemies and cannot be healed (even if they are in your party).

**Comment by dimitriskolios** [comment]
Alright it makes sense then.
However, the ElvUi party frames do not have this "issue" regardless of outer world. Is there a way I can configure my Grid to have the same behaviour perhaps?

**Comment by michaelnpsp** [comment]
Goto Statuses/Targeting&Distances/Range configuration and use a different range setup, for example 38 yards instead on Heal Range.
Another option is to unlink the range status from the alpha indicator (in indicators tab).
Another option is to enable the range status only inside instances (goto statuses/Targeting&Distances/range/load tab/Instance option and select only instances)

**Comment by dimitriskolios** [comment]
The first option you suggested fixed the issue! 
thank you
