### ISSUE TITLE
Boss Unit Frame colors

### ISSUE THREAD

**Issue by mikeekert** [michaelnpsp/Grid2#169]
Checking to see if it is possible to color the Boss frames according to their friend/foe status?

Showing the health as a Red color for friends, and then mark friendly boss units (ones you need to heal, specifically) as green health bars?

**Comment by michaelnpsp** [comment]
I dont understand your setup, do you want red color for friendly players ?
You can create a second bar indicator configured to display a different color status (for example friendcolor instead of classcolor) and enable this bar indicator only for bosses.  The friendcolor status allows to customize different colors for friends/enemies.
To display a specific indicator only for bosses, goto the "Load" tab in the indicator configuration and filter the indicator by "Unit Type", selecting "Bosses" units.

**Comment by mikeekert** [comment]
Oh!  Sorry, I mistyped.

Basically I want enemy units in the Boss Unit list to be red health bars (or some easy way to denote they are hostile), and then any friendly units in the encounter to be green.

From what I could Friendcolor made everything green (the name makes sense). 

Basically the issue is a Boss frames list grabs everything in the encounter that Blizzard lists with a boss id, so it shows both.  As a healer, I really just care about the friendlies.  As there is no way to filter out the hostile units, I'm trying to just mark them as less visually distracting, and make the friendly units more noticeable.

**Comment by michaelnpsp** [comment]
Despite the name, friendcolor makes hostiles red. (the color for friend and hostile units can be customized from statuses/colors/friendcolor).
So if  you simply want friends: green, hostiles: red,  you dont need to create a second bar indicator, simply use friendcolor status to colorize  the main health bar.
