### ISSUE TITLE
Cataclysm - Wrong Incoming direct heals values

### ISSUE THREAD

**Issue by SilAntoine** [michaelnpsp/Grid2#238]
Hello,

I noticed that incoming direct heals values are wrong and messing up both text and healthbar displays.
I fixed default SpellIDs that were wrong in buff statuses (from SpellID to SpellName) but I'm guessing to fix heals-incoming and my-heals-incoming status I'd have to edit your code.

HoTs values are fine (even Regrowth HoT portion) but direct heals values are way bigger than they should be.

Is there a way I can share my druid profile to make sure it's actually the addon and not my settings that are messed up (I reinstalled the addon to no avail).

Thanks for your hard work, I love grid! :D

Kind regards,
Antoine

**Comment by michaelnpsp** [comment]
It's a bug in the game client. The game is reporting wrong heal values.
You can setup a heal-multiplier value to reduce the heals in the heals-incominh status configuration, but that can not full fix the issue because each heal spell is off by a different amount some heals are 30x bigger others only 5x bigger.

**Comment by SilAntoine** [comment]
Thanks for your answer, I'm glad it's just the game.
They'll fix it eventually.
