### ISSUE TITLE
Feature request: Default frame position when reloading in combat

### ISSUE THREAD

**Issue by Anghammar** [michaelnpsp/Grid2#249]
Hello!

Currently, when reloading the UI in combat, the unite frames does not position themself correctly until you leave combat. I assume this is because Grid2 s utilizing some API calls for positioning that is not available during combat. It would be nice to have some less complex positioning algorithm that is usable in combat for initial positioning, so that you can at least make sure your frames don't get stuck behind some other frames in your UI even if the sorting etc. is wrong until you leave combat.

Thank you for maintaining this addon.

**Comment by michaelnpsp** [comment]
You simply have to use a non-center alignment/position for the frames: TOPLEFT, TOPRIGHT, BOTTOMLEFT, or BOTTOMRIGHT.
With a CENTER setting is not possible to set the final posistion of the frames because usually  the information required to center the window is not available before the game locks the movement of all unit frames due to combat restrictions.

**Comment by Anghammar** [comment]
Ah, so it was the alignment that was the culprit. It's a bummer, since I really like having non-full parties be centered. I guess my feature request still stands though: a fallback non-center alignment (with adjustable horizontal slider so it fit nicely to your UI) usable in combat (when using centered alignment as default).

Personally I will just try to get used to non-center alignment, but maybe I'll do a PR for this one day who knows.

Thank you for the quick response.
