### ISSUE TITLE
[Feature Request] Blacklist debuffs by modifier+right clicking on them

### ISSUE THREAD

**Issue by kerriganx** [michaelnpsp/Grid2#252]
Currently you can't blacklist debuffs "on the fly", you have to wait when fight finished then manually add needed auras to blacklist.
It's annoying when you come to new boss and see all the crap on raid frames. When I see debuff I don't want to see I usually screenshot it to remove later or start screen recording with combat log enabled, then watch to see how clean my raid frames looks and what I need to remove. It can be especially annoying in dungeons where are too many useless trash debuffs, screenshoting them takes a lot of time.
It would be great if we could simply right click on debuff to blacklist it. Maybe add modifier like Ctrl+Shift+Click.

This is implemented in ElvUI and Cell raid frames, would love to see this in Grid2 too, the one feature I really missing.

**Comment by michaelnpsp** [comment]
Grid2 does not manage keybindings/click casting, because this usually done by another addons like Clique or using the standard interface and mouser macros
I added a grid2 command line option to add/remove the spell/aura of the current displayed tooltip to the blacklist/white list of a debuffs status.
This command line option can be used in macros or in Clique, the syntax is:

`/grid2 parsetip [status_name]`

The command works with any tooltip displayed so you can assign a general keybinding to the macro and capture the aura/spell of any tooltip (not only grid2 tooltips).

Examples: 

`/grid2 parsetip`
This option looks for a debuffs status in the grid2 current profile and add /remove the spell/aura of the current visible tooltip.

`/grid2 parsetip MyDebuffs`
If the profile has several debuffs statuses defined, the status name can be specified in the command line option. In the above example the debuffs-MyDebuffs status will be used.








if you have a "debuffs-MyDebuffs" status created, you must create a macro like:
/grid2 parsetip MyDebuffs
or you can use the general
