### ISSUE TITLE
Cataclysm: Multibars->"heal-absorbs" / HealingPrevented not available? 

### ISSUE THREAD

**Issue by c3pomagneto** [michaelnpsp/Grid2#254]
hello,

so i was reading the fantastic tutorials at https://michaelnpsp.github.io/grid2-murloc-guide/#multibar on multibars and tried to set one up myself like shown on the tutorial:
![grid2](https://github.com/user-attachments/assets/9de1e2fb-0a6b-4310-8df7-6e66149eb4e9)

could it be that cataclysm does not support setting up heals-absorb? in mthe multibar menu i got the main, the incoming heals and shields, but HealingPrevented, HealingReduced didnt work.  i also noticed that by default there is no "heals-absorb" indicator, i just want to make sure to learn as much as i can about that fantastic addon.

thanks and sorry for bothering.

**Comment by michaelnpsp** [comment]
Aborbs re not available in classic versions because Blizzard dediced to hide/restrict that information in classic clients.
Full shields information is hidden too but Grid2 implementa a limited version of shields status manual tracking some priest, paladin, and mage spells, so shields information in cataclysm could not be accurate due to game restrictions.

**Comment by c3pomagneto** [comment]
thank you very much for taking the time to explain this topic in detail!
