### ISSUE TITLE
[Feature request][TBC] Multibar incoming healing priority

### ISSUE THREAD

**Issue by vladoffic** [michaelnpsp/Grid2#28]
Greetings! 

Is it possible to add a dynamic priority system to the multibar?
For example: Priorities of "tail" bars will be determined by the FIFO rule. If an other healer begins to heal earlier than me then an "other incoming healing" bar will get higher priority than "my incoming healing" bar. 

Thanks!

![1](https://user-images.githubusercontent.com/89085825/129749910-0f3f96dc-3b47-4cf9-97cd-b33fdb76cedc.PNG)

**Comment by illogicz** [comment]
Would like to see this feature standard myself.
For a couple years now I have modified Grid2 by adding a status called "pre-heals" which is the amount of incoming heals before my current direct heal will land. And then you are able to use this status this in a multibar to achieve what you are asking for.

In case the developers are interested in adding something like this, this is the meat of the logic I used:

```	
	UnitGetPreHeals = function(unit)
		local guid = UnitGUID(unit)
		local ownHealTime, ownHealFrom, ownHealAmount = HealComm:GetNextHealAmount(guid, HealComm.DIRECT_HEALS, GetTime() + preheals_timeband, nil, playerGUID)
		if not ownHealTime then
			return 0
		end
		local preheal = HealComm:GetHealAmount(guid, HealComm.ALL_HEALS, ownHealTime - 0.001) or 0
		preheal = preheal * (HealComm:GetHealModifier(guid) or 1)
		preheal = heals_cache[unit] - preheal -- inverse so it can be used with a multibar
		return preheal or 0
	end
```
I did have to kind of invert the value since anchoring to the topmost bar did not seem to work.

**Comment by michaelnpsp** [comment]
HealCom library was abandoned, and now allmost all addons are using the blizzard heals api. Unfortunatelly the blizzard api is very simple and does not provide enough information to implement this feature.
