### ISSUE TITLE
Grid2 sometimes shows only first 2 out of 5 groups on zoning in

### ISSUE THREAD

**Issue by xCharg** [michaelnpsp/Grid2#41]
Not sure how to reproduce the issue, but every once in a while, after a wipe, when I load back into the raid, Grid2 only displays less than half a raid (two groups out of 5 groups).

/reload fixes it

How to proceed troubleshooting that issue?

**Comment by michaelnpsp** [comment]
Which game client do you use (vanilla/tbc/retail) ? Which instances ? Which Grid2 version ?

You can go to General/About Tab,  Debugging Section, and Click on "Grid2" Option.
Then when the issue happends post here the debug message Grid2 should display on chat, something like this:
_"Grid2: DEBUG GroupChanged ZONE_CHANGED_NEW_AREA Sanguine Depths 2284 sparty other 5 => party mythic 5"_

**Comment by xCharg** [comment]
English classic TBC client, Grid2 2.0.32-bcc

Turned on debug messaging, didn't catch the bug yet.
However I noticed that every time I zone in any instance - grid thinks i'm switching to raid10 mode and then back to raid 25, not sure if that supposed to happen?

[20:12:20] Grid2: DEBUG Grid2 GroupChanged PLAYER_ENTERING_WORLD Black Temple 564 nil none 40 => raid other 10 
[20:12:22] Changed Channel: [1. General - Black Temple] 
[20:12:22] Grid2: DEBUG Grid2 GroupChanged ZONE_CHANGED_NEW_AREA Black Temple 564 raid other 10 => raid other 25

**Comment by michaelnpsp** [comment]
The game client is bugged and sometimes is returning wrong information (the players caps for some instances) in classic clients. Grid version 2.0.33 implements a workaround to this issue:
https://www.wowace.com/projects/grid2/files/3636998
The workaround is not perfect: entering an old vanilla 40man instance (like onyxia lair) from the tbc client detects a 25man (instead of a 40man). But to code a perfect fix i should implement a big lookup table with all classic instances instead of trusting the game information. The real fix should by blizzard fixing his game, but unfortunatelly this is not going to happen.
