### ISSUE TITLE
Position wrong after someone leaves a group and someone else joins

### ISSUE THREAD

**Issue by jimmycuadra** [michaelnpsp/Grid2#5]
Hello! I'm having an issue with the position of Grid's frames after someone leaves a dungeon group and another player joins from the queue. I took screenshots to demonstrate because it's a little hard to explain.

I have Grid positioned to the left of my player unit frame, so normally it looks like this during a 5-player dungeon:

<img width="748" alt="grid_correct" src="https://user-images.githubusercontent.com/122457/104376499-f29ddb00-54d9-11eb-9211-e9da2f2129bd.png">

After someone leaves and rejoins, the grid squares are shifted to the right and overlap my player unit frame:

<img width="755" alt="grid_incorrect" src="https://user-images.githubusercontent.com/122457/104376583-0c3f2280-54da-11eb-9767-1b5d86115aeb.png">

Here are the settings I'm using. The goal is for grid frames to appear above the bottom row as more players are added in larger groups.

<img width="514" alt="grid_settings" src="https://user-images.githubusercontent.com/122457/104376613-195c1180-54da-11eb-8052-bbddc79c7007.png">

Is this unexpected behavior? If not, how should I configure Grid to prevent this? I haven't noticed the problem in LFR, just 5-player dungeons.

Thanks much for the addon! It's invaluable, especially when playing a healer.

**Comment by michaelnpsp** [comment]
That usually happens in vertical or horizontal centered frames  if you are in combat when a player leaves or joins because due to game restrictions unit frames can not be resized. 
Due to the same restrictions is advised to not move the frames during combat, because during frame drag the game changes the anchor point and the addon cannot fix and readjust the anchor point in combat.
If you wan to avoid that behaviour you have to use a BOTTOMLEFT / TOPLEFT /TOPRIGHT/BOTTOMRIGHT anchors instead of TOP/BOTTOM/LEFT/RIGHT anchors.

**Comment by jimmycuadra** [comment]
Thanks for the reply! I'm already using frame lock, so it's not an accidental drag. I'll try using a corner-based anchor and see if I can get it to behave the way I'd like.
