### ISSUE TITLE
Wrong bar texture on load

### ISSUE THREAD

**Issue by Rezurekt74** [michaelnpsp/Grid2#71]
Hey Michael,

I'm rocking Grid2 and I love it, great work ! I have small issue that appeared randomly : whenever the addon is loaded, either on login or /reload, the bar textures of the raid frames are reset to the wrong texture, not the one specified in the indicators nor the one in the default values. I use a texture from another addon (raven). It's still the correct texture in the settings, but not the one that actually loads. It behaves the same way if I choose a texture from Grid2 , like Grid2Flat. I couldn't find a similar problem on forums or reddit, so I'm coming directly to you. 

Ishnu-alah,

Mathieu

**Comment by michaelnpsp** [comment]
Raven addon is registering the textures to the sharedmedia library too late in the addon load process. When Grid2 is enabled Raven textures are not available yet. Raven maintained should register the textures earlier (in the addon load or initialize process).

**Comment by Rezurekt74** [comment]
Is there a way to copy this texture inside Grid2 with the others ? Or something as dumb as renaming Raven higher up in the alphabet to be loaded before Grid2 (if addons load in alphabetical order) ?

**Comment by michaelnpsp** [comment]
The addons load order does not matter because grid2 already load the textures after all other addons were loaded (to give time to other addons to initialize the textures). 
Maybe you could ask the raven maintainer to register the textures early, Its a single line change in **Main.lua** file, he only have to move the line:
**MOD:InitializeMedia(media)**
that is inside the **MOD:OnEnable()** function to the  **MOD:OnInitialize()** function.

**Comment by Rezurekt74** [comment]
That solved it ! Thank you very much, you're the best !
