### ISSUE TITLE
Incoming Heals

### ISSUE THREAD

**Issue by robertac93** [michaelnpsp/Grid2#72]
I am currently only seeing direct-cast heals (such as regrowth) show up as incoming heals. No hots are being shown as incoming heals anymore, which they used to prior to the Wrath updates. Any idea on if there is just some setting that has changed, or is there some API issue with showing hots now? I no longer see Lifebloom, Rejuvenation, the hot from regrowth, or Wild Growth.

Thanks!!

**Comment by michaelnpsp** [comment]
Grid2 now uses the Blizzard API, Blizzard API does not support HOTs. In previous expansions Grid2 was using LibHealComm4 library to display heals and hots but this library is unmaintained and there is no version for wrath.

**Comment by vuryn** [comment]
There is a working fork of LibHealComm-4.0 for Wrath [here](https://github.com/Azilroka/LibHealComm-4.0). 
I have just tested it on live Wrath servers by replacing Grid's version checks "<30000" with "<40000" and it worked as a drop-in replacement. 
It even showed incoming heals of other healers without the patched version, so it seems to be compatible with the original LibHealComm.
The only bug I could find was prematurely cancelling Penance (a channeled heal), which had the heal prediction stuck until the next heal event.

I'd really appreciate it if there was some toggle option to use this patched lib instead of the Blizzard API, even if it would be slightly buggy.

**Comment by michaelnpsp** [comment]
There is serveral forks of the library (mostly unmaintained), but I cannot use personal forks. That fork has no license so legally i cannot include that code in Grid2.

**Comment by vuryn** [comment]
The repository above is owned by [Azilroka](https://github.com/Azilroka). Given the fact that he is on the author list of [LibHealComm on Curse](https://www.curseforge.com/wow/addons/libhealcomm-4-0/files) since Classic release (check the .toc files), I don't think that is a personal fork.

[Grid's own LICENSE.txt](https://github.com/michaelnpsp/Grid2/blob/main/LICENSE.txt) mentions ShestakUI as source of LibHealComm, which also has [a commit from 5 days ago](https://github.com/EsreverWoW/ShestakUI_Classic/blob/master/ShestakUI/Libs/LibHealComm-4.0/LibHealComm-4.0.lua) containing version checks for Wrath builds and Wrath spell names like Penance and Wild Growth.

**Comment by michaelnpsp** [comment]
ShestakUI UI has an opensource license compatible with Grid2 license (this was the last libhealcomm4 library grid2 included), but it has no fixes for the last libhealcom4 bugs.
I dont care about the owner of the code i care if i have permission to use the code. Without direct permission from the author or a compatible license with Grid2 license i have no permission to use that code.

**Comment by robertac93** [comment]
I see that you've made the fix to include the LibHealComm-4.0 library. I apologize for my *complete* noobness, but what do I need to download from github and move into my Classic Addons folder to get it working? I normally just install addons through Curseforge, I know its a stupid question. I downloaded the commit that had the changes, but the folder structure didn't see to quite align with what was in my addon folder already.

**Comment by michaelnpsp** [comment]
The source code of the repo cannot be easily used because a lot of files are missing there (external libraries). The final package is created using the bigwigs package manager, but I did not package a new version yet because i have to fully test the changes.

**Comment by michaelnpsp** [comment]
Version 2.0.52-wrath including new healcomm4 library is available for download now.
