### ISSUE TITLE
"Toggle for vehicle" not working on wrath

### ISSUE THREAD

**Issue by EmElw** [michaelnpsp/Grid2#76]
Tested using the dragon vehicles in the Oculus, fresh profile which by default has "Toggle for vehicle", no other addons enabled.

Expected behaviour: player enters vehicle, frame instead reflects vehicle and can be used to target the vehicle
Observed behaviour: frame visually unchanged, becomes uninteractable, i.e. cannot be clicked on to target the player nor vehicle. However still shows tooltip. The behaviour is the same if toggle for vehicle is toggled off.

Some things I've tried
 - in GridFrame:365, in the UNIT_ENTERED_VEHICLE handler, `new` is always equal to `old` which seems like it'd clearly cause problems
 - in the exit handler, the pet doesn't have any frames to iterate over so there'd be no mechanism for resetting the frame to show the player again

**Comment by michaelnpsp** [comment]
Unfortunatelly toggleForVehicle does not work because blizzard forgot to reenable all the code to manage vehicles, for example SecureButton_GetModifiedUnit() should return the vehicle unit but all the vehicle switch code was commented and always return the player unit. This bug can be tracked here:
https://github.com/Stanzilla/WoWUIBugs/issues/274
Unfortunatelly i dont know any workaround for this issue,  i could change the code to display the pet info instead of player info, but the click for tageting or healing on the unit frames are going anyway to be applied to the players and not the vehicles, becouse the real change of the unit must be done by the comented blizzard code (addons cannot change the units in combat only blizzard code can do that).

**Comment by EmElw** [comment]
Okay good to know that its a blizz issue. Thanks!

**Comment by michaelnpsp** [comment]
I implemented a workaround in version 2.0.55-beta, but its ugly and not perfect, the real fix must be provided by a blizzard patch in the game client. Important:

1. "Use Blizzard Raid Frames" option in General/Layouts must be ENABLED.

2. The fix is only enabled in Malygos and Oculus instances.

3. Targeting is only fixed for Grid2 default left-click, this means clique targeting/heals or mouseover macros are not going to work. If you have bindings for healing/targeting in clique for left-click, you are overriding the default grid2 left-click so this workaround are not going to work. To avoid this issue without removing clique keybindings, you can use some modifier leftclick not used in clique for targeting, valid mouse/keybindings for targeting are: LeftClick, SHIFT-LeftClick, CTRL-LeftClick or ALT-LeftClick.

**Comment by whichwit** [comment]
This worked well when I tried EoE last night. No need for secondary pet frames. Thank you. I don't know how ugly the code is for the temporary fix, at least we have a solution for now.
