### ISSUE TITLE
Feature Request: Copy Indicator

### ISSUE THREAD

**Issue by missiah** [michaelnpsp/Grid2#88]
I have a Theme for M+ with kind of big Icons
Would love the be able copy all my indicator so i can setup a Theme for 40 BG and lower the indicator size for it

Right now i would have to create every indicator again one by one and select it in the Raid Theme

It would be cool have it like that:
Indicator: icon-db
copy
result:
icon-db
icon-db2

now i just could select the icon-db2 in my Raid Theme and just lower the size a bit and not have to create every idicator from scratch.

**Comment by michaelnpsp** [comment]
It is overkilling to duplicate all the indicators. 
- You can go to de Indicators section of each theme and setup a different icon size. Then in each icon indicator  select "Default"  in the icon Size combobox instead of "Pixels", in this way the indicators will use the icon size defined on each theme.
- If you are using different frame sizes for each theme, you can select in the Icon size combobox of each icon indicator the "Percent" value , in this way the size of the icon is defined as a percent of the frame height, in this way for different frame sizes the icons will automatic adjust its size.

**Comment by missiah** [comment]
Alright it works, thanks
