### ISSUE TITLE
Party order

### ISSUE THREAD

**Issue by gonstr** [michaelnpsp/Grid2#90]
Hey. Great Addon. I love everything about it and I use it for raids as well as for partying and doing arena.

In Arena, I use keybinds to target myself and party members. I have set keybinds for target self and target party member 1 and party member 2:

![grid](https://user-images.githubusercontent.com/1374839/204165031-bb6ffd95-542d-4f3d-8764-523be96f1a21.png)

Now, the problem is that there is no layout in Grid2 that matches this ordering from what I understand, so when you join Arena, the group is pretty much scrambled, or if you have chosen to layout by class, role, etc it's in that order. In any case, it becomes very hard to know which keybind will target which player.

Is there a way to order the boxes when I'm in a party or in arena so that it's always like this:

[player][party member 1][party member 2][party member 3][party member 4]

Where the ordering matches the keybinds for target self, party member 1, party member 2, etc.

Thanks,
Tom

**Comment by michaelnpsp** [comment]
Use any "By Group" layout, and uncheck the "Sort units by Name" option in General/Layouts.

**Comment by gonstr** [comment]
Right. So the "By Group" works exactly like what I want.

I see the problem now. The problem is specific to Arena. When you join arena as a party, it makes the group in to a raid for some reason, scrambling the group order.

The keybinds still work though, with target self, party member 1 and 2, even though that's not how the group necessarily is ordered in the raid.

Is there anyway to make Grid2 still display it "By Group" in arena, i.e with the **player** always first, and then the party members in order, even though the game turns the group in to a raid in Arena?

**Comment by michaelnpsp** [comment]
Yes, in a custom layout you can setup a list with: player, part1, party2, units etc. 
The player unit is going to work because always exists even in raid. what i dont remember is if the game creates the  party1, party2, etc while in arena.
You can enter an arena and type into chat:
/script print( UnitExists('party1'))
if this little code displays:
true
then a custom layout should work.

**Comment by gonstr** [comment]
The macro works and prints `true` both inside and outside arena for both `player`, `party1`, etc but when I create a layout like this and switch to it, the grid just dissapearsand shows nothing:

![custom](https://user-images.githubusercontent.com/1374839/204540907-2494f083-373b-4995-ac0d-c55b49865706.png)

Can't get this to work outside arena or inside. What am I doing wrong?

**Comment by michaelnpsp** [comment]
I see the issue. That is a namelist, a list of player names, you have to create a custom header.
1. Click on the little Tab with the "Plus" sign near players(1) Tab, to create a new header.
2. A "Create new Header" page will be displayed.
3. In the New Header Type, select "Custom" instead of "Players"
4. Click Create
5. Type the units in the "Units List" Edit Box.
6. Goto the players(1) header  scroll down, and click Delete, to delete this header.

**Comment by gonstr** [comment]
That worked, thanks :)

I do have a suggestion for improvement though. If you choose any "By Group" layout, it should do this ordering inside arena, similar to how it does for parties outside arena.

Nice that it's possible to create this through custom header though. You can close this issue if you want.
