### ISSUE TITLE
OmniCC not working with "square" indicators.

### ISSUE THREAD

**Issue by mcdastar** [michaelnpsp/Grid2#95]
As title says, omnicc doesnt work for square indicators. Can't we just add this feature or at least clock shadow timer as shown in this screenshot: https://imgur.com/wcQWfSL

OmniCC or shadow clock timer works for icons but some of us use squares for hot tracking :/

**Comment by michaelnpsp** [comment]
OmniCC only works with cooldown animations, square dont have this feature.  Use an icon indicator configured to display squares instead .
1. Create an icon indicator or convert your square indicator to an icon indicator (Layout tab "Indicator Type" option).
2. Goto to the "Icon" section and enable  the "Display Square" option. In this way the icon will display a square instead of the buff/debuff icon.
