### ISSUE TITLE
Can't detach frames

### ISSUE THREAD

**Issue by midavisbiz** [michaelnpsp/Grid2#96]
I see that I can detach frames using custom layouts.  However, I want to be able to move those and size those independently.  I would love to have separate tank frames

**Comment by midavisbiz** [comment]
I guess I just don't understand how to do this.  I went into the editor and created 2 tabs for my LFR theme.  The first I have selected 1/2/3 and everything but MT and MA.  The other tab I have selected 1/2/3 and Tank.  I then added a layout for a 15 main instance and added the name of my layout (I am not sure if I am supposed to do this or not).   In tab 2 I detached my header (I am not sure if I am supposed to do this).  I also clicked on Detach all groups in General and removed Frame Lock in Layout Look & Feel.  I changed the border 10 so I can see the spacing and give me something to drag.  I am unable to move any of these groups separately or at all

**Comment by michaelnpsp** [comment]
To be able to move the layout you must activate the desired layout first.
You can use the "magnifying glass" icon next to the each layout selected in "Layouts"/"By Group Type" tab to enable a layout for testing purposes or to adjust the layout position.
If you use the "By Raid Size" tab to select layouts, there is a "Test" button there too, to activate the layouts.
I dont understand the 15 man instance thing you talked about, because LFR instances are 30 man raids, so if you selected a layout for 15 man instances, this layout is not going to be activated in LFR.
You can check which layout is activated holding the mouse pointer over the Grid2 minimap icon: a tooltip is displayed with useful information, like which profile/theme/layout are activated.
